global:
  scrape_interval: 15s
  evaluation_interval: 1m
  external_labels:
    prometheus: compose-test-1

remote_write:
  - url: http://thanos-receive-0:19291/api/v1/receive

scrape_configs:

  - job_name: prometheus_scrape
    static_configs:
      - targets: [localhost:9090]

  - job_name: thanos-receive
    static_configs:
      - targets:
        - thanos-receive-0:10902
        - thanos-receive-1:10902
