global:
  scrape_interval: 5s
  evaluation_interval: 1m
  external_labels:
    prometheus: compose-test-1
    location: eu-west-1
    site: prod

remote_write:
  - url: http://nginx:8080/api/v1/receive
    basic_auth:
      username: foo
      password: bar

#alerting:
#  alertmanagers:
#    - static_configs:
#        - targets:
#            - webhook.site
#      path_prefix: /c4712942-0397-4c3e-9c1f-a5d95f28f36e
#      scheme: https
#rule_files:
#  - /cfg/rules.yml

scrape_configs:

  - job_name: prometheus_scrape
    static_configs:
      - targets: [localhost:9090]
        labels:
          site: prom

  - job_name: thanos-receive
    static_configs:
      - targets:
        - thanos-front:10902
        - thanos-receive-0:10902
        - thanos-receive-1:10902
        labels:
          site: than

  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]
        labels:
          site: node
