global:
  scrape_interval: 5s
  evaluation_interval: 1m
  external_labels:
    prometheus: compose-test-1
    location: eu-west-1
    site: prod

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [localhost:9090]
        labels:
          site: prom
