global:
  scrape_interval: 5s
  evaluation_interval: 1m

remote_write:
  - url: http://thanos-front:19291/api/v1/receive
    headers:
      THANOS-TENANT: a

scrape_configs:
  - job_name: prometheus_scrape
    static_configs:
      - targets: [localhost:9090]
        labels:
          site: prom

  - job_name: thanos-receive
    static_configs:
      - targets:
        - thanos-front:10902
        - thanos-receive-0:10902
        - thanos-receive-1:10902
        labels:
          site: than

  - job_name: node-exporter
    static_configs:
      - targets: [node-exporter:9100]
        labels:
          site: node
