version: '2.4'
services:

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.44.0
    command:
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver #/api/v1/write
      - --config.file=/cfg/prometheus.yml
      - --storage.tsdb.path=/data
      - --storage.tsdb.retention.time=15m
      - --storage.tsdb.min-block-duration=15m
      - --storage.tsdb.max-block-duration=15m
      - --enable-feature=memory-snapshot-on-shutdown
    volumes:
      - ./cfg/prometheus.yml:/cfg/prometheus.yml
      - ./data/prometheus:/data
    user: '65534'
    ports:
      - '9090:9090'

  otel:
    container_name: otel
    hostname: otel
    image: otel/opentelemetry-collector-contrib:0.78.0
    command:
      - --config=/cfg/otel.yml
    volumes:
      - ./cfg/otel.yml:/cfg/otel.yml
    ports:
      - 4318:4318