version: '2'
services:

  # Go Carbon (Carbon replacement)
  # Takes care of writing metrics to database and data retention
  go-carbon:
    container_name: go-carbon
    image: go-carbon
    build:
      dockerfile: go-carbon.dockerfile
      context: .
    command: -config=/etc/go-carbon/go-carbon.conf
    volumes:
      - ./configs:/etc/go-carbon
      - ./whisper:/data/graphite/whisper/

  # Graphite API (yep, almost original Graphite Web)
  # Provides API for reading metrics
  graphite-api:
    container_name: graphite-api
    image: brutasse/graphite-api:latest
    environment:
      GRAPHITE_API_CONFIG: /etc/graphite-api/graphite-api.yaml
    volumes:
      - ./configs:/etc/graphite-api
      - ./whisper:/data/graphite/whisper
    depends_on:
      - go-carbon

  # Grafana
  # Metrics dashboard
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./configs:/etc/grafana
      - ./grafana:/var/lib/grafana
      - ./logs:/var/log/grafana
    depends_on:
      - graphite-api