version: '2.4'
services:

  thanos-receive-0:
    container_name: thanos-receive-0
    hostname: thanos-receive-0
    image: thanosio/thanos:v0.15.0
    command:
      - receive
      - --tsdb.path=/data
      - --tsdb.retention=1d
      - --label=replica="thanos-receive-0"
      - --receive.local-endpoint=thanos-receive-0:10901
      - --receive.hashrings-file=/cfg/hashrings.json
      - --receive.replication-factor=2
    volumes:
      - ./cfg/hashrings.json:/cfg/hashrings.json
      - ./data/thanos-receive-0:/data
    user: '65534'

  thanos-receive-1:
    container_name: thanos-receive-1
    hostname: thanos-receive-1
    image: thanosio/thanos:v0.15.0
    command:
      - receive
      - --tsdb.path=/data
      - --tsdb.retention=1d
      - --label=replica="thanos-receive-1"
      - --receive.local-endpoint=thanos-receive-1:10901
      - --receive.hashrings-file=/cfg/hashrings.json
      - --receive.replication-factor=2
    volumes:
      - ./cfg/hashrings.json:/cfg/hashrings.json
      - ./data/thanos-receive-1:/data
    user: '65534'

  thanos-query:
    container_name: thanos-query
    hostname: thanos-query
    image: thanosio/thanos:v0.15.0
    command:
      - query
      - --query.auto-downsampling
      - --query.partial-response
      - --query.replica-label=replica
      - --query.replica-label=tenant_id
      - --store=dns+thanos-receive-0:10901
      - --store=dns+thanos-receive-1:10901
    user: '65534'
    ports:
    - 10902:10902

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/cfg/prometheus.yml
      - --storage.tsdb.path=/data
      - --storage.tsdb.retention.time=1d
      - --storage.tsdb.min-block-duration=15m
      - --storage.tsdb.max-block-duration=15m
    volumes:
      - ./cfg/prometheus.yml:/cfg/prometheus.yml
      - ./data/prometheus:/data
    user: '65534'
    ports:
    - '9090:9090'

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:7.1.0
    entrypoint:
      - /usr/share/grafana/bin/grafana-server
      - --homepath=/usr/share/grafana
      - --config=/cfg/grafana.ini
    volumes:
      - ./cfg/grafana.ini:/cfg/grafana.ini
      - ./cfg/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./cfg/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./cfg/dashboards:/var/lib/grafana/dashboards
    ports:
      - '3000:3000'
