version: '2'
services:

  mimir:
    container_name: mimir
    hostname: mimir
    image: grafana/mimir:2.7.1
    command:
      - -auth.multitenancy-enabled=false
      - -ingester.ring.replication-factor=1
    ports:
      - '8080:8080'

  prometheus:
    container_name: prometheus
    hostname: prometheus
    image: prom/prometheus:v2.43.0
    command:
      - --config.file=/cfg/prometheus.yml
    volumes:
      - ./prometheus.yml:/cfg/prometheus.yml
    ports:
      - '9090:9090'

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    volumes:
      - ./metrics:/usr/share/nginx/html/metrics
      - ./metrics2:/usr/share/nginx/html/metrics2
    ports:
      - '8081:80'