{
 "title": "Host: overview",
 "tags": [
  "mon",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "prometheus",
    "query": "label_values(node_exporter_build_info,prometheus)"
   },
   {
    "name": "instance",
    "query": "label_values(node_filesystem_avail_bytes{prometheus=~\"$prometheus\"}, instance)"
   },
   {
    "name": "mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime: $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "instance",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_boot_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode=\"idle\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "repeat": "instance",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_exporter_build_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk utilization: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} out"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} in"
    }
   ]
  },
  {
   "title": "IO/s: $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} read/s"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} write/s"
    }
   ]
  }
 ]
}