{
 "title": "Host: overview",
 "tags": [
  "mon",
  "node"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "prometheus",
    "query": "label_values(node_exporter_build_info,prometheus)"
   },
   {
    "name": "instance",
    "query": "label_values(node_filesystem_avail_bytes{prometheus=~\"$prometheus\"}, instance)"
   },
   {
    "name": "mountpoint",
    "query": "label_values(node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}, mountpoint)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime: $instance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "repeat": "instance",
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_boot_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode=\"idle\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 0 },
   "repeat": "instance",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_uname_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "node-exporter",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "node_exporter_build_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "CPU usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by(mode) (irate(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode!=\"idle\"}[$__interval]))",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LA/Core: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(node_load15{prometheus=~\"$prometheus\", instance=~\"$instance\"})/count(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "15m"
    },
    {
     "expr": "avg(node_load5{prometheus=~\"$prometheus\", instance=~\"$instance\"})/ count(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "5m"
    },
    {
     "expr": "avg(node_load1{prometheus=~\"$prometheus\", instance=~\"$instance\"})/ count(node_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\", mode=\"idle\"})",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Memory: $instance",
   "type": "graph",
   "description": "PageCache: ActiveFile + InactiveFile\nBuffers: Relatively temporary storage for raw disk blocks (ex. ext4 journal)\nCached: PageCache - Buffers\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_Active_file_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_Shmem_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_Inactive_file_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_SReclaimable_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_MemFree_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg(node_memory_Active_file_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} + node_memory_Shmem_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "ActiveFile"
    },
    {
     "expr": "avg(node_memory_Inactive_file_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} + node_memory_SReclaimable_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_Buffers_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "InactiveFile"
    },
    {
     "expr": "avg(node_memory_Buffers_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Buffers"
    },
    {
     "expr": "avg(node_memory_MemFree_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Free"
    },
    {
     "expr": "avg(node_memory_SwapTotal_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Disk utilization: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_io_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Filesystem used: $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} / node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(mountpoint, device)",
     "legendFormat": "{{mountpoint}} = {{device}}"
    }
   ]
  },
  {
   "title": "IO/s: $instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "repeat": "instance",
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_disk_reads_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} read/s"
    },
    {
     "expr": "avg(rate(node_disk_writes_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} write/s"
    }
   ]
  },
  {
   "title": "Network usage: $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_network_transmit_bytes_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} out"
    },
    {
     "expr": "avg(rate(node_network_receive_bytes_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(device)",
     "legendFormat": "{{device}} in"
    }
   ]
  },
  {
   "title": "Network Sockstat: $instance",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_netstat_Tcp_CurrEstab{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "avg(node_sockstat_TCP_tw{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "avg(node_sockstat_sockets_used{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "avg(node_sockstat_UDP_inuse{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "avg(node_sockstat_TCP_alloc{prometheus=~\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "TCP_alloc"
    }
   ]
  },
  {
   "title": "Filesystem Usage: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
     "repeat": "mountpoint",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Size {{device}} {{fstype}} ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "1 - node_filesystem_files_free{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} / node_filesystem_files{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Inodes used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Size {{device}} {{fstype}} ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "1 - node_filesystem_files_free{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} / node_filesystem_files{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Inodes used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$mountpoint usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Size {{device}} {{fstype}} ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "node_filesystem_size_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} - node_filesystem_avail_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "1 - node_filesystem_files_free{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"} / node_filesystem_files{prometheus=~\"$prometheus\", instance=~\"$instance\", mountpoint=~\"$mountpoint\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Inodes used on {{mountpoint}}",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Misc: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 241 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Processes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "avg_over_time(node_procs_running{prometheus=~\"$prometheus\", instance=~\"$instance\"}[5m]) - 1",
       "legendFormat": "Runnable Processes"
      },
      {
       "expr": "avg_over_time(node_procs_blocked{prometheus=~\"$prometheus\", instance=~\"$instance\"}[5m])",
       "legendFormat": "Blocked Processes"
      },
      {
       "expr": "irate(node_forks_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[5m])",
       "legendFormat": "Created Processes (Forks)"
      }
     ]
    },
    {
     "title": "Interrupts and Context Switches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_context_switches_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "irate(node_intr_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Interrupts"
      }
     ]
    },
    {
     "title": "Swap Space",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapFree_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_SwapTotal_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"} - node_memory_SwapFree_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "Bps", "label": "Swap out (-) / Swap in (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "irate(node_vmstat_pswpin{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "calculatedInterval": "2s",
       "expr": "irate(node_vmstat_pswpout{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "TCP Retransmission",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_netstat_Tcp_RetransSegs{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "Segments Retransmitted"
      },
      {
       "expr": "scalar(rate(node_netstat_Tcp_RetransSegs{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))/sum(rate(node_network_transmit_packets_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "Retransmit Ratio"
      }
     ]
    },
    {
     "title": "Local Network Errors",
     "type": "graph",
     "description": "Total Number of Local Network Interface Transmit Errors, Receive Errors and Drops.  Should be  Zero",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "sum(irate(node_network_receive_errs_total{prometheus=~\"$prometheus\", instance=~\"$host\", device!=\"lo\"}[5m]))",
       "legendFormat": "Receive Errors"
      },
      {
       "expr": "sum(irate(node_network_transmit_errs_total{prometheus=~\"$prometheus\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Transmit Errors"
      },
      {
       "expr": "sum(irate(node_network_receive_drop_total{prometheus=~\"$prometheus\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Receive Drop"
      },
      {
       "expr": "sum(irate(node_network_transmit_drop_total{prometheus=~\"$prometheus\", instance=~\"$instance\", device!=\"lo\"}[5m]))",
       "legendFormat": "Transmit Drop"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{prometheus=~\"$prometheus\", instance=~\"$instance\"}[5m])",
       "legendFormat": "ListenOverflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{prometheus=~\"$prometheus\", instance=~\"$instance\"}[5m])",
       "legendFormat": "ListenDrops"
      }
     ]
    },
    {
     "title": "Disk IO Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(sum(irate(node_disk_read_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])) / sum(irate(node_disk_reads_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])))",
       "legendFormat": "Read Latency"
      },
      {
       "expr": "(sum(irate(node_disk_write_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])) / sum(irate(node_disk_writes_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])))",
       "legendFormat": "Write Latency"
      },
      {
       "expr": "(sum(rate(node_disk_read_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[1h])) / sum(rate(node_disk_reads_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[1h])))",
       "legendFormat": "Avg Read Latency (1h)"
      },
      {
       "expr": "(sum(rate(node_disk_write_time_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[1h])) / sum(rate(node_disk_writes_completed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[1h])))",
       "legendFormat": "Avg Write Latency (1h)"
      }
     ]
    },
    {
     "title": "Conntrack",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_nf_conntrack_entries{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
       "legendFormat": "entries"
      },
      {
       "expr": "node_nf_conntrack_entries_limit{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  }
 ]
}