{
 "title": "Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "prometheus",
    "query": "label_values(prometheus_build_info, prometheus)"
   },
   {
    "name": "instance",
    "query": "label_values(prometheus_build_info{prometheus=\"$prometheus\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "first",
   "targets": [
    {
     "expr": "prometheus_build_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Config reloaded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - prometheus_config_last_reload_success_timestamp_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Reload ok",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Alertmanagers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_notifications_alertmanagers_discovered{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Remote-write lag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - prometheus_remote_storage_highest_timestamp_in_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "singlestat",
   "description": "The current number of queries being executed or waiting.",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(prometheus_engine_queries{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "Total number of connections failed to dial by the dialer a given name.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(net_conntrack_dialer_conn_failed_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(dialer_name, reason)",
     "legendFormat": "{{dialer_name}}/{{reason}}"
    },
    {
     "expr": "avg(rate(prometheus_rule_evaluation_failures_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "rule_evaluation"
    },
    {
     "expr": "avg(rate(prometheus_sd_consul_rpc_failures_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "sd_consul"
    },
    {
     "expr": "avg(rate(prometheus_sd_dns_lookup_failures_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "dns_lookup"
    },
    {
     "expr": "avg(rate(prometheus_sd_file_read_errors_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "sd_file"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_exceeded_sample_limit_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "exceeded_sample_limit"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "duplicate_timestamp"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_out_of_bounds_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "out_of_bounds"
    },
    {
     "expr": "avg(rate(prometheus_target_scrapes_sample_out_of_order_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "out_of_order"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "mcache"
    },
    {
     "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "mspan"
    },
    {
     "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Profiling"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Heap used"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "Heap idle"
    },
    {
     "expr": "avg(process_resident_memory_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "RSS"
    }
   ]
  },
  { "title": "Remote write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Failed samples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(prometheus_remote_storage_failed_samples_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "avg(rate(prometheus_remote_storage_dropped_samples_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "dropped"
    },
    {
     "expr": "avg(rate(prometheus_remote_storage_enqueue_retries_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "queue full"
    },
    {
     "expr": "avg(rate(prometheus_remote_storage_retried_samples_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "resent"
    }
   ]
  },
  {
   "title": "Queued samples",
   "type": "graph",
   "description": "The number of samples pending in the queues shards to be sent to the remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(prometheus_remote_storage_pending_samples{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Samples rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(rate(prometheus_remote_storage_samples_in_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "avg(rate(prometheus_remote_storage_succeeded_samples_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "RemoteWrite Latency",
   "type": "heatmap",
   "description": "Duration of sample batch send calls to the remote storage.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "avg(rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])) by(le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "8*avg(rate(prometheus_remote_storage_sent_bytes_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "graph",
   "description": "The number of shards that the queues shard calculation wants to run based on the rate of samples in vs. samples out.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(prometheus_remote_storage_shards{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "shards"
    },
    {
     "expr": "avg(prometheus_remote_storage_shards_desired{prometheus=\"$prometheus\", instance=~\"$instance\"})",
     "legendFormat": "desired"
    }
   ]
  },
  {
   "title": "Query",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query timings",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(prometheus_engine_query_duration_seconds{prometheus=\"$prometheus\", instance=~\"$instance\",quantile=\"0.9\"}[$__interval]))by(slice)",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Http requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(prometheus_http_requests_total{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(handler,code)",
       "legendFormat": "{{handler}}: {{code}}"
      }
     ]
    },
    {
     "title": "Rule evaluation time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_duration_seconds{prometheus=\"$prometheus\", instance=~\"$instance\"}[$__interval])",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Targets discovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(prometheus_sd_discovered_targets{prometheus=\"$prometheus\", instance=~\"$instance\", name=\"scrape\"})by(config)",
       "legendFormat": "{{config}}"
      }
     ]
    },
    {
     "title": "TSDB chunks",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{prometheus=\"$prometheus\", instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  }
 ]
}