{
 "title": "Thanos: receive",
 "tags": [ "thanos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "prometheus",
    "query": "label_values(thanos_build_info,prometheus)"
   },
   {
    "name": "instance",
    "query": "label_values(thanos_receive_replication_factor{prometheus=~\"$prometheus\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "first",
   "targets": [
    {
     "expr": "thanos_build_info{prometheus=~\"$prometheus\", instance=~\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(time() - process_start_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "TSDB block loaded",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(prometheus_tsdb_blocks_loaded{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "TSDB failed compactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(prometheus_tsdb_compactions_failed_total{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "WAL corruptions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(prometheus_tsdb_wal_corruptions_total{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bucket",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "thanos_objstore_bucket_last_successful_upload_time{prometheus=~\"$prometheus\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Last block upload",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 1 },
   "format": "s",
   "valueName": "first",
   "targets": [
    {
     "expr": "min(time() - thanos_objstore_bucket_last_successful_upload_time{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Hashring nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "first",
   "targets": [
    {
     "expr": "min(thanos_receive_hashring_nodes{prometheus=~\"$prometheus\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "HTTP server",
   "type": "graph",
   "description": "Prometheus remote-write requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(handler,code)",
     "legendFormat": "{{handler}}/{{code}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(process_cpu_seconds_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GRPC server",
   "type": "graph",
   "description": "Thanos cross-component communication",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(grpc_code,grpc_method)",
     "legendFormat": "{{grpc_method}}/{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(process_resident_memory_bytes{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Metrics by Prometheus",
   "type": "graph",
   "description": "Amount of unique metrics (cardinality) received from each Prometheus",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(job:metrics:count) by(prometheus)",
     "legendFormat": "{{prometheus}}"
    }
   ]
  },
  { "title": "TSDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "PVC usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_used_bytes{prometheus=~\"$prometheus\", persistentvolumeclaim=~\"thanos-receive-data-.*\"}",
     "legendFormat": "used {{persistentvolumeclaim}}"
    },
    {
     "expr": "min(kubelet_volume_stats_capacity_bytes{prometheus=~\"$prometheus\", persistentvolumeclaim=~\"thanos-receive-data-.*\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Samples/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_tsdb_head_samples_appended_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(instance) >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TSDB chunks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(instance) >0",
     "legendFormat": "chunks: {{instance}}"
    },
    {
     "expr": "time() - prometheus_tsdb_head_min_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"} and prometheus_tsdb_head_min_time_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"} < 9223372036854776",
     "legendFormat": "head_time: {{instance}}"
    }
   ]
  },
  {
   "title": "Series",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(instance) >0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "GRPC Series Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "avg(rate(grpc_server_handling_seconds_bucket{grpc_method=\"Series\", prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])) by(le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "HTTP bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "8*sum(rate(http_request_size_bytes_sum{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(code)",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "GRPC RemoteWrite Latency",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "avg(rate(grpc_server_handling_seconds_bucket{grpc_method=\"RemoteWrite\", prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval])) by(le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "HTTP success requests",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{prometheus=~\"$prometheus\", instance=~\"$instance\", code=\"200\"}[$__interval]))by(instance)\n/\nsum(rate(http_requests_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bucket operations",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(thanos_objstore_bucket_operations_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Forward rps",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(thanos_receive_forward_requests_total{prometheus=~\"$prometheus\", instance=~\"$instance\"}[$__interval]))by(result)",
       "legendFormat": "{{result}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  },
  {
   "title": "Go Stats: $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Go Heap",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_mcache_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mcache"
      },
      {
       "expr": "avg(go_memstats_mspan_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "mspan"
      },
      {
       "expr": "avg(go_memstats_buck_hash_sys_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Profiling"
      },
      {
       "expr": "avg(go_memstats_heap_inuse_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap used"
      },
      {
       "expr": "avg(go_memstats_heap_idle_bytes{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "Heap idle"
      }
     ]
    },
    {
     "title": "GC CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "avg(go_memstats_gc_cpu_fraction{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "gc_cpu"
      }
     ]
    },
    {
     "title": "Go Routines",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(go_goroutines{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "goroutines"
      },
      {
       "expr": "avg(go_threads{prometheus=\"$prometheus\", instance=~\"$instance\"})",
       "legendFormat": "threads"
      }
     ]
    },
    {
     "title": "Go GC duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(go_gc_duration_seconds{prometheus=~\"$prometheus\", instance=~\"$instance\"})by(quantile)",
       "legendFormat": "{{quantile}}q"
      }
     ]
    }
   ]
  }
 ]
}